name: Deploy
on:
  push:
    branches: ['main']

jobs:
  deploy-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - name: Deploy App
        uses: zcloud-ws/zcloud-deploy-action@main
        with:
          env-token: ${{ secrets.QUAVE_CLOUD_ENV_TOKEN }}
          env: "joaovictornsv-github-activity-card-production"
